apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 30   # min number of seconds for a which newly created pod should be ready
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:  # template for pods with selector. However, now pods are named by replicaset so we don't need name
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
        - name: webapp
        - image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue  # This field is for service to select this app.
    release: "0"  # Use this to upgrade version without down time. We create a second pod with a new release and after it is running, we change the service selector after
spec:
  containers: 
    - name: queue
    - image: richardchesterwood/k8s-fleetman-queue:release1