kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name:  new-joiner
rules:
- apiGroups: [""]  # "" inidcates the core API group
  resources: ["pods", "services"]  # use "*" for resources available in the apiGroup
  verbs: ["get", "list", "watch"]  # watch shows output when there are changes.

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: put-specfic-user-or-users-into-new-joiner-role
  namespace: default
subjects:
  # List users are going into this role, can have many
- kind: User
  name: francis-linux # custome name
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io/v1