apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp  # This field is for service to select this app.
    release: "0"  # Use this to upgrade version without down time. We create a second pod with a new release and after it is running, we change the service selector after
spec:
  containers: 
    - name: webapp
    - image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp  # This field is for service to select this app.
    release: "0-5"  # Use this to upgrade version without down time. We create a second pod with a new release and after it is running, we change the service selector after
spec:
  containers: 
    - name: webapp
    - image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
